-- ==============================================================================
-- GAME VAULT DATABASE ALL-IN-ONE CONSOLIDATED SCHEMA
-- Jalankan seluruh script SQL ini di Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. TABEL: app_users (Manajemen Akun & Role Pengguna)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('pembeli_akun', 'penjual_akun', 'admin')),
    nama TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_users_email ON public.app_users (email);
CREATE INDEX IF NOT EXISTS idx_app_users_role ON public.app_users (role);

-- ==============================================================================
-- 3. TABEL: app_settings (Pengaturan Sistem & Kunci Rahasia Admin)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default Secret Key Admin
INSERT INTO public.app_settings (key, value)
VALUES ('admin_secret_key', 'admin123')
ON CONFLICT (key) DO NOTHING;

-- ==============================================================================
-- 4. TABEL: accounts (Master Stok Akun Game, Pembelian & Penjualan)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    game TEXT DEFAULT 'Belum Diisi',
    username TEXT DEFAULT '-',
    buy_price NUMERIC DEFAULT 0,
    sell_price NUMERIC DEFAULT 0,
    is_sold BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'ON_BOOK', 'SOLD')),
    locked_by TEXT,
    bought_by TEXT,
    sold_by TEXT,
    buyer_email TEXT DEFAULT '-',
    buy_proof_url TEXT,
    proof_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    sold_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_accounts_status ON public.accounts (status);
CREATE INDEX IF NOT EXISTS idx_accounts_is_sold ON public.accounts (is_sold);
CREATE INDEX IF NOT EXISTS idx_accounts_email ON public.accounts (email);
CREATE INDEX IF NOT EXISTS idx_accounts_created_at ON public.accounts (created_at ASC);

-- ==============================================================================
-- 5. TABEL: account_inbox (Penyimpanan Pesan Masuk & Kode OTP di Database)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.account_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_email TEXT NOT NULL,
    sender TEXT DEFAULT 'System',
    subject TEXT DEFAULT 'No Subject',
    body_text TEXT DEFAULT '',
    message_id TEXT,
    received_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_account_inbox_email ON public.account_inbox (account_email);
CREATE INDEX IF NOT EXISTS idx_account_inbox_received ON public.account_inbox (received_at DESC);

-- ==============================================================================
-- 6. STORAGE BUCKET: account-proofs (Bukti Transaksi & Bukti Beli)
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('account-proofs', 'account-proofs', true)
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE POLICY "Public Access account-proofs"
ON storage.objects FOR SELECT
USING (bucket_id = 'account-proofs');

CREATE POLICY "Public Insert account-proofs"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'account-proofs');

CREATE POLICY "Public Update account-proofs"
ON storage.objects FOR UPDATE
USING (bucket_id = 'account-proofs');

-- ==============================================================================
-- 7. ROW LEVEL SECURITY (RLS) & ACCESS PERMISSIONS
-- ==============================================================================
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_inbox ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to app_users"
ON public.app_users FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to app_settings"
ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to accounts"
ON public.accounts FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all access to account_inbox"
ON public.account_inbox FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.app_users TO anon, authenticated;
GRANT ALL ON TABLE public.app_settings TO anon, authenticated;
GRANT ALL ON TABLE public.accounts TO anon, authenticated;
GRANT ALL ON TABLE public.account_inbox TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
